environment: production
environmentCode:
name: ffc-pay-dps
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-dps

labels:
  component: service

appInsights:
  connectionString:

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

containerConfigMap:
  name: ffc-pay-dps-config-map

containerSecret:
  name: ffc-pay-dps-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  azureStorageAccountName: ffcpay
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  messageQueueHost: namespace.servicebus.windows.net
  fileSendTopicAddress: ffc-pay-file-send
  eventsTopicAddress: ffc-pay-events
  customerTopicAddress: ffc-pay-customer
  customerSubscriptionAddress: ffc-pay-dps
  storageContainer: batch
  storageFolder: inbound
  storageDaxContainer: dax
  storageDaxFolder: outbound
  useEvents: true
  processingActive: true
  pollingInterval: 60000
  port: 3013
  azureLogLevel: error

postgresService:
  postgresDb: ffc_pay_dps
  postgresqlHost: ffc-pay-dps-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

readinessProbe:
  path: /healthy
  port: 3013
  initialDelaySeconds: 60
  periodSeconds: 120
  failureThreshold: 5
  timeoutSeconds: 30

livenessProbe:
  path: /healthz
  port: 3013
  initialDelaySeconds: 70
  periodSeconds: 120
  failureThreshold: 5
  timeoutSeconds: 30

workloadIdentity: true

secretProviderClass:
  azure:
    keyvaultName: SNDFFCINFKV2001
    objects: # reading the secret from Azure Key Vault
      - objectName: appInsights-connectionString # secret name in Azure Key Vault
        objectType: secret

  secretObjects: # creating a Kubernetes secret from the Azure Key Vault secrets
    - secretName: ffc-pay-dps
      type: Opaque
      data:
        - objectName: appInsights-connectionString # secret name in Azure Key Vault
          key: APPLICATIONINSIGHTS_CONNECTION_STRING # the secret key in the Kubernetes secret and use in the application