name: Secret Scanner

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened        # PR created
      - synchronize   # new commits pushed to an existing PR
      - reopened      # PR reopened after being closed

jobs:
  secret-scan:
    uses: DEFRA/ffc-shared-actions/.github/workflows/secret-scanner.yml@main
    secrets: inherit